### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [timomak/CS-1.3#1]
- While your LinkedStack looks good, your choice for the head of ArrayStack is inefficient. Doing any manipulations to the 0 index of an array is O(n) time complexity; I highly recommend using operations that affect the end of the list to get an O(1) time complexity.
- Nice work on your Set class. I would have liked to seen a size property on the Set itself because it was a part of the challenges, but the `length` function is similar in functionality. Be careful in your `intersection` method, as you are close to an optimization by iterating over the smaller list, but you end up iterating over the larger list, which un-optimizes your code. In addition, some of your time complexities are off; your methods are more efficient than you think they are. For example, in `difference`, you iterate over `n` keys, and calling `contains` and `add` are close to constant time complexity. If you add everything up, you get O(n) time complexity for just iterating over those `n` keys.
- Your set tests are a good start, but you might consider varying the input to use integers or multi-character strings, as I have already seen this break someone's code. I also recommend not relying on just the `length` of the set in `test_intersection` to see if it worked; I think you should check the actual values inside of the set as well.

**Comment by timomak** [comment]
I think I fixed all of these and have re submitted the form.
